/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/badges': typeof BadgesRoute
  '/certificate': typeof CertificateRoute
  '/playground': typeof PlaygroundRoute
  '/progress': typeof ProgressRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/badges': typeof BadgesRoute
  '/certificate': typeof CertificateRoute
  '/playground': typeof PlaygroundRoute
  '/progress': typeof ProgressRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules': typeof ModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/badges': typeof BadgesRoute
  '/certificate': typeof CertificateRoute
  '/playground': typeof PlaygroundRoute
  '/progress': typeof ProgressRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/badges'
    | '/certificate'
    | '/playground'
    | '/progress'
    | '/modules/$slug'
    | '/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/badges'
    | '/certificate'
    | '/playground'
    | '/progress'
    | '/modules/$slug'
    | '/modules'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/badges'
    | '/certificate'
    | '/playground'
    | '/progress'
    | '/modules/$slug'
    | '/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  BadgesRoute: typeof BadgesRoute
  CertificateRoute: typeof CertificateRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProgressRoute: typeof ProgressRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  BadgesRoute: BadgesRoute,
  CertificateRoute: CertificateRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProgressRoute: ProgressRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
